support oracle
huandu/go-sqlbuilder pull request #126
Opened 2023-09-12 08:05 UTC by zhangyongding

2023-09-15 02:33 UTC, huandu commented
Thanks for your contribution. I need some time to review this PR. I'll give you feedback by the end of Sep.

2023-10-31 13:51 UTC, zhangyongding commented
已经经过完整测试，请问是否可以考虑合并？

2023-11-01 05:46 UTC, huandu commented
@zhangyongding 好的，非常感谢，我会在这周合并。代码 review 我已经基本看完了，问题不大，主要是希望去掉 `Struct` 的 `*WithTag` 相关方法，你可以看一下代码，类似名字的函数都已经标记为 deprecated，后续也不要再增加类似函数了。

2023-11-01 05:48 UTC, huandu requested changes

2023-11-01 05:48 UTC, huandu commented on struct.go
> +func (s *Struct) ForeachReadForTag(tag string, trans func(dbtag string, isQuoted bool, field reflect.StructField)) {
不要提供这样的接口，应该统一使用 `s.withTags` 和 `s.withoutTags` 来做 tag 过滤，下同。

2023-11-02 00:29 UTC, zhangyongding commented
已经移除ForeachReadForTag和ForeachWriteForTag函数

2023-11-03 12:39 UTC, huandu approved these changes

2023-11-03 12:40 UTC, merged

2023-11-04 06:43 UTC, huandu commented
refs #118