Add CQL support
huandu/go-sqlbuilder pull request #85
Opened 2022-09-08 18:41 UTC by SpencerC

* Add CQL flavor.

* Add support for CQL argument compilation.

* Adopt substests for interpolation tests.

* Add support for CQL interpolation.

* Add support for CQL blobs.

https://docs.datastax.com/en/cql-oss/3.x/cql/cql_reference/blob_r.html

* Add CQL timestamp interpolation support.

https://docs.datastax.com/en/cql-oss/3.x/cql/cql_reference/timestamp_type_r.html

* Add builder test for CQL.

* Add support for the NOW function.

https://docs.datastax.com/en/cql-oss/3.3/cql/cql_reference/timeuuid_functions_r.html?hl=now

* Add support for CQL update IF statement.

https://docs.datastax.com/en/cql-oss/3.3/cql/cql_reference/cqlUpdate.html#Conditionallyupdatingcolumns

* Drop table prefixes for CQL SELECTs.

* Switch to single quoting for CQL queries.

https://docs.datastax.com/en/cql-oss/3.3/cql/cql_reference/escape_char_r.html

* Update documentation.

* Use valid CQL in tests.

* Support CQL LIMIT.

2022-09-09 04:19 UTC, huandu requested changes
Thanks a lot for your contribution. I leave some review comments here. We can discuss in this PR thread.

2022-09-09 04:19 UTC, huandu commented on modifiers.go
> +func Now() interface{} {
It's not recommended to add this method. There are tons of functions in every DBMS. `NOW()` is not the one which is extremely outstanding and must be added in this package.

BTW, SQLServer doesn't have `NOW()`. The equivalent one is `SYSDATETIME()`.

2022-09-09 04:19 UTC, huandu commented on update.go
> +func (ub *UpdateBuilder) If(andExpr ...string) *UpdateBuilder {
It's not recommended to add this method. `IF` is a CQL-specific extension. AFAIK, there is no other DBMS supporting this. I recommend you to implement this in your CQL business code.

```go
func CQLUpdateIf(ub *sqlbuilder.UpdateBuilder, andExpr ...string) *sqlbuilder.UpdateBuilder {
    ub.SQL("IF")
    ub.SQL(strings.Join(andExprs, " AND "))
    return ub
}
```

As you can see, this package mainly defines methods for keywords available in ISO SQL-2016 spec, which is a subset of all DBMS implementations, with a few exceptions. I do think it's not convenient for users who build SQL with only one flavor. There is a long standing issue #60 (in Chinese) in which the support to `ON DUPLICATE KEY UPDATE` is requested. I cannot resolve this issue as SQL syntax for duplicate key differs a lot in different DBMS. It's hard to define a unified method for this feature.

A possible way to support flavor-specific keywords is to create sub-package for every flavor, e.g. `github.com/huandu/go-sqlbuilder/cql` for CQL, and then define methods based on the flavor's SQL spec. However, there will be a lot of work to do so.

2022-09-21 07:59 UTC, huandu commented
@SpencerC Could you update your PR per my review comments? Feel free to comment on my comments.

2022-09-21 11:32 UTC, SpencerC commented
Yep, have some other work to finish first.

2022-09-22 01:59 UTC, huandu commented
Got it.

2023-01-06 03:58 UTC, huandu requested changes
There are some compile errors in test case. Please fix them. Thanks.

2023-01-09 21:34 UTC, SpencerC commented
Apologies, should be fixed now.

2023-01-11 11:27 UTC, huandu commented
LGTM. Thanks a lot for your time, @SpencerC !

2023-01-11 11:27 UTC, merged

2023-01-11 11:28 UTC, huandu reviewed
LGTM.