feat: Support ClickHouse Grammar
huandu/go-sqlbuilder pull request #92
Opened 2022-12-12 09:42 UTC by hanyuancheung

- Support ClickHouse basic grammar.

2022-12-12 09:49 UTC, hanyuancheung commented
hi @huandu 
I've found that sqlbuilder still not support clickhouse grammar, so I contribute this part to use this tool to generate sql statement. Could you please to review it, thanks.

2022-12-13 06:45 UTC, huandu requested changes

2022-12-13 06:45 UTC, huandu commented on interpolate.go
> +				buf = append(buf, "_binary"...)
I don't find `_binary` method in ClickHouse doc. Instead, I find [`unhex`](https://clickhouse.com/docs/en/sql-reference/functions/encoding-functions#unhex) seems the most appropriate method to convert arbitrary data to blob. You can try to write logic against `unhex`, or you can provide me a pointer to `_binary` if this method works well in ClickHouse.

2022-12-13 06:45 UTC, huandu commented on flavor.go
> +		ib.verb = "INSERT"
The verb should be `INSERT INTO`. And it also should be `INSERT INTO` in PostgreSQL flavor -- it should be an aged bug.

2022-12-13 06:46 UTC, huandu commented
Thanks for your contribution! Please review my feedback and make changes. Feel free to discuss with me if you have any question.

2022-12-13 08:05 UTC, hanyuancheung commented
> Thanks for your contribution! Please review my feedback and make changes. Feel free to discuss with me if you have any question.

Thanks for ur reply. I've fixed these comments.

2022-12-14 12:02 UTC, huandu requested changes
There are still some blocking issues. Please fix them. Thanks.

2022-12-14 12:02 UTC, huandu commented on interpolate.go
> +				buf = append(buf, "unhex"...)
The `unhex` is a function. Don't forget the parens. Per doc, it should be called like `unhex("ab1234")`.

2022-12-14 12:02 UTC, huandu commented on interpolate.go
> +				buf = quoteStringValue(buf, *(*string)(unsafe.Pointer(&data)), flavor)
Call `appendHex` instead `quoteStringValue`.

2022-12-14 12:02 UTC, huandu commented on interpolate_test.go
> +			"SELECT TRUE, FALSE, 1.234567, 9.87654321, NULL, _binary'I\\'m bytes', '2019-04-24 12:23:34.123457', '0000-00-00', NULL", nil,
Don't forget to update case to cover `[]byte` type. And try the expected SQL in your ClickHouse environment to make sure the SQL really works well.

2022-12-15 03:38 UTC, hanyuancheung commented
> There are still some blocking issues. Please fix them. Thanks.

Sure, I've fixed them and tested in my local clickhouse. It works well. Thanks for the advice.

2022-12-15 07:51 UTC, huandu approved these changes
LGTM.

2022-12-15 08:04 UTC, merged